// ✨ AI Summary Card — the actual artifact the doctor sees, shown on the
// homepage. Red-flag chips, triage score, queue position, sources. Static
// mock (CSS stagger only — no client JS), English-only, no external assets.

export function AiSummaryCard() {
  return (
    <div className="mx-auto max-w-2xl">
      <div className="rounded-[26px] bg-[#fffdf7] p-6 shadow-[0_24px_60px_rgba(0,0,0,0.35)] ring-1 ring-[#0f5c61]/20">
        {/* header */}
        <div className="flex flex-wrap items-center justify-between gap-2 border-b border-[#1b1712]/10 pb-3">
          <p className="inline-flex items-center gap-2 text-sm font-bold text-[#08363a]">
            ✨ AI Clinical Summary
          </p>
          <span
            className="rounded-full bg-[#f6f0e4] px-2.5 py-0.5 text-[10px] font-semibold text-[#4a4338]"
            title="Generated by our AI lane with rule-based grounding — every field cites its source"
          >
            engine: groq · grounded · sources cited
          </span>
        </div>
        <p className="mt-2 text-xs text-[#4a4338]">
          Token MED-0055 · General Medicine · Shivanna, 67 / Male · ABHA linked
        </p>

        {/* red-flag chips */}
        <div className="mt-4 flex flex-wrap gap-2">
          <span
            className="rise inline-flex items-center gap-1.5 rounded-full bg-[#b42318] px-3 py-1.5 text-xs font-bold text-white shadow-sm"
            style={{ animationDelay: "0.15s" }}
          >
            ⚠️ Penicillin allergy
          </span>
          <span
            className="rise inline-flex items-center gap-1.5 rounded-full bg-[#b42318] px-3 py-1.5 text-xs font-bold text-white shadow-sm"
            style={{ animationDelay: "0.35s" }}
          >
            ⚠️ β-blocker + asthma interaction
          </span>
          <span
            className="rise inline-flex items-center gap-1.5 rounded-full bg-[#c9842a] px-3 py-1.5 text-xs font-bold text-white shadow-sm"
            style={{ animationDelay: "0.55s" }}
          >
            🚨 Chest pain — triage rule RF-ACS-01
          </span>
        </div>

        {/* summary fields */}
        <div className="mt-5 space-y-3 text-sm">
          <div>
            <p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#c9842a]">
              Chief complaint
            </p>
            <p className="mt-0.5 text-[#08363a]">
              Chest pain since 2 days with sweating, radiating to left arm.
            </p>
          </div>
          <div>
            <p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#c9842a]">
              History (AI-written, doctor-editable)
            </p>
            <p className="mt-0.5 leading-relaxed text-[#1b1712]">
              67-year-old man, sudden onset, severity 8/10. Known Type 2 Diabetes +
              Hypertension on Metformin and Telmisartan. No previous cardiac workup.
              Red-flag rule fired: chest pain + diaphoresis + left-arm radiation.
            </p>
          </div>
        </div>

        {/* triage score strip */}
        <div
          className="rise mt-5 rounded-2xl bg-[#08363a] p-4 text-[#f6f0e4]"
          style={{ animationDelay: "0.75s" }}
        >
          <div className="flex flex-wrap items-center justify-between gap-2">
            <p className="text-sm font-bold">
              <span className="rounded-full bg-[#b42318] px-2.5 py-0.5 text-xs uppercase tracking-wider">
                Priority: High
              </span>
            </p>
            <p className="text-sm font-semibold tabular-nums">Queue position 3 of 18</p>
          </div>
          {/* position bar: 3 of 18 */}
          <div className="mt-3 h-2.5 w-full overflow-hidden rounded-full bg-white/15">
            <div className="h-full w-[17%] rounded-full bg-[#e8d5a3]" />
          </div>
          <p className="mt-2 text-xs text-[#f6f0e4]/70">
            ⚡ Skips ahead of 15 routine patients — a heart attack never waits in queue.
          </p>
        </div>

        {/* footer */}
        <p className="mt-4 text-center text-xs text-[#4a4338]">
          ✓ Doctor confirms or amends in one tap · every field cites its source
        </p>
      </div>

      <p className="mt-3 text-center text-[11px] uppercase tracking-[0.18em] text-[#f6f0e4]/50">
        Also generated in Hindi + Kannada · honest template fallback if AI is down
      </p>
    </div>
  );
}