"use client";

import type { AyushAssessment, ClinicalSummary, Consent, Document, HistoryResponse, HisEvent, Patient, Session } from "@/db/schema";
import { DEPARTMENTS } from "@/lib/types";
import { generateAbdmFhirBundle } from "@/utils/fhirMapper";
import { useRouter } from "next/navigation";
import { useMemo, useState } from "react";

type Bundle = {
  session: Session;
  patient: Patient;
  answers: HistoryResponse[];
  documents: Document[];
  summary: ClinicalSummary | null;
  consents: Consent[];
  events: HisEvent[];
};

const FIELDS: { key: keyof ClinicalSummary; label: string }[] = [
  { key: "chiefComplaint", label: "Chief complaint" },
  { key: "hpi", label: "History of present illness" },
  { key: "pastMedical", label: "Past medical history" },
  { key: "pastSurgical", label: "Past surgical history" },
  { key: "drugs", label: "Drug history" },
  { key: "allergies", label: "Allergies" },
  { key: "familyHistory", label: "Family history" },
  { key: "personalHistory", label: "Personal history" },
  { key: "reviewOfSystems", label: "Review of systems" },
  { key: "investigationsSummary", label: "Prior investigations" },
  { key: "medicationsExtracted", label: "Medicines on papers" },
];

export function ReviewWorkspace({ bundle, reviewer }: { bundle: Bundle; reviewer?: string }) {
  const router = useRouter();
  const { session, patient, documents, summary, consents, events } = bundle;
  const [fields, setFields] = useState<Record<string, string>>(() => {
    const init: Record<string, string> = {};
    if (summary) {
      for (const f of FIELDS) {
        const v = summary[f.key];
        if (typeof v === "string") init[f.key] = v;
      }
    }
    return init;
  });
    const [notes, setNotes] = useState(session.physicianNotes ?? "");
  // Doctor's advice FOR the patient — shown in their portal after confirm
  const [advice, setAdvice] = useState(
    (summary?.patientAdvice as string | undefined) ?? ""
  );
  const [reviewedBy, setReviewedBy] = useState(session.reviewedBy ?? reviewer ?? "");
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");

  const [genBusy, setGenBusy] = useState(false);
  const [genStatus, setGenStatus] = useState<{
    message: string;
    kind: "ok" | "error" | "info";
  } | null>(null);
  const [showFhir, setShowFhir] = useState(false);
  const [fhirJson, setFhirJson] = useState<any>(null);
  const [showBilingual, setShowBilingual] = useState(false);

  const labs = useMemo(() => {
    return documents.flatMap((d) =>
      (d.extractedJson?.labs ?? []).map((lab) => ({
        ...lab,
        when: d.documentDate,
        facility: d.facilityName,
      })),
    );
  }, [documents]);

  const timeline = useMemo(() => {
    return [...documents].sort((a, b) => (a.documentDate ?? "").localeCompare(b.documentDate ?? ""));
  }, [documents]);

  async function generateSummary() {
    setGenBusy(true);
    setGenStatus({ message: "Summarising the interview... (AI or local fallback) - Groq: openai/gpt-oss-120b, Gemini: gemini-2.0-flash", kind: "info" });
    try {
      const res = await fetch(`/api/sessions/${session.id}/summary`, { method: "POST" });
      const data = await res.json();
      if (!res.ok) {
        setGenStatus({ message: data.error || "Failed to generate summary", kind: "error" });
      } else if (data.aiUsed) {
        const engineName =
          data.engine === "ollama"
            ? "Ollama"
            : data.engine === "groq"
              ? "Groq (openai/gpt-oss-120b)"
              : data.engine === "gemini"
                ? "Gemini (gemini-2.0-flash)"
                : "AI";
        setGenStatus({ message: `Summary generated by ${engineName}. Confidence: High, Bilingual ready`, kind: "ok" });
      } else {
        setGenStatus({
          message: `AI was attempted but returned nothing${
            data.aiError ? ` (${data.aiError.slice(0,200)})` : ""
          } - used the built-in local generator instead. Check GROQ_MODEL env var.`,
          kind: "info",
        });
      }
      router.refresh();
    } catch (e) {
      setGenStatus({ message: "Summary generation failed. Check Vercel logs.", kind: "error" });
    } finally {
      setGenBusy(false);
    }
  }

  function viewFhirBundle() {
    try {
      const bundle = generateAbdmFhirBundle({
        abhaId: patient.abhaId || "91-0000-0000-0000",
        patientName: patient.fullName,
        gender: (patient.gender as any) || "other",
        age: patient.age,
        chiefComplaints: [summary?.chiefComplaint || ""],
        diagnoses: documents.flatMap(d => d.extractedJson?.diagnoses || []),
        medications: documents.flatMap(d => d.extractedJson?.medications?.map(m => m.name) || []),
        allergies: summary?.allergies ? [summary.allergies] : [],
      });
      setFhirJson(bundle);
      setShowFhir(true);
    } catch (e) {
      console.error("FHIR generation failed", e);
    }
  }

  async function save(confirm: boolean) {
    if (!summary) return;
    setBusy(true);
    setMessage("");
    try {
      await fetch(`/api/sessions/${session.id}/summary`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          fields,
          status: confirm ? "confirmed" : "draft",
          reviewedBy,
          physicianNotes: notes,
          patientAdvice: advice,
        }),
      });
      setMessage(confirm ? "Confirmed and filed to HIS / ABHA." : "Draft amendments saved.");
      router.refresh();
    } finally {
      setBusy(false);
    }
  }

  const dept = DEPARTMENTS.find((d) => d.id === session.department)?.label ?? session.department;
  const ayush = summary?.ayushAssessment as AyushAssessment | null;

  return (
    <main className="mx-auto grid max-w-7xl gap-8 px-6 py-8 lg:grid-cols-[1fr_320px]">
      <div>
        <div className="flex flex-wrap items-start justify-between gap-4">
          <div>
            <p className="text-xs uppercase tracking-[0.2em] text-[#c9842a]">
              {dept} / {session.mode}
            </p>
            <h1 className="serif mt-1 text-4xl">{patient.fullName}</h1>
            <p className="mt-2 text-sm text-[#4a4338]">
              {patient.age} years / {patient.gender} / {patient.phone ?? "no phone"} /{" "}
              {patient.abhaId ? `ABHA ${patient.abhaId}` : "ABHA not linked"}
            </p>
          </div>
          <div className="ticket rounded-3xl px-6 py-4 text-center">
            <p className="text-[10px] uppercase tracking-[0.18em] text-[#4a4338]">Token</p>
            <p className="serif text-3xl text-[#08363a]">{session.tokenNumber}</p>
            <p className="mt-1 text-xs uppercase">{session.priority}</p>
          </div>
        </div>

        {session.redFlagTriggered && (
          <aside className="mt-6 rounded-3xl bg-[#b42318] px-5 py-4 text-white">
            <p className="text-xs uppercase tracking-[0.16em] text-white/70">Red flags from kiosk</p>
            <ul className="mt-2 list-disc space-y-1 pl-5 text-sm">
              {(session.redFlagReasons ?? []).map((r) => (
                <li key={r}>{r}</li>
              ))}
            </ul>
          </aside>
        )}

        {!summary && (
          <div className="mt-8 space-y-4">
            <div className="rounded-[28px] bg-[#fffdf7] p-6 ring-1 ring-[#1b1712]/8">
              <p className="text-xs uppercase tracking-[0.16em] text-[#c9842a]">AI summary</p>
              <h2 className="serif mt-1 text-2xl">Generate clinical summary</h2>
              <p className="mt-2 text-sm text-[#4a4338]">
                This session has no summary yet. Generate one now - it will draft the structured notes from the
                interview (and documents). You can edit everything before confirming to HIS / ABHA.
              </p>
              <button
                type="button"
                disabled={genBusy}
                onClick={() => void generateSummary()}
                className="mt-4 inline-flex items-center gap-2 rounded-full bg-[#0f5c61] px-6 py-3 font-semibold text-white transition hover:bg-[#08363a] disabled:opacity-50"
              >
                {genBusy ? (
                  <>
                    <span className="h-4 w-4 animate-spin rounded-full border-2 border-white/40 border-t-white" />
                    Generating...
                  </>
                ) : (
                  "Generate summary"
                )}
              </button>
              {genStatus && (
                <p
                  className={`mt-3 text-sm ${
                    genStatus.kind === "error"
                      ? "text-[#b42318]"
                      : genStatus.kind === "ok"
                        ? "text-[#1f6b45]"
                        : "text-[#8a5a18]"
                  }`}
                >
                  {genStatus.message}
                </p>
              )}
            </div>
          </div>
        )}

        {summary && (
          <div className="mt-8 space-y-5">
            <div className="flex flex-wrap items-center justify-between gap-3">
              <p className="text-xs uppercase tracking-[0.16em] text-[#c9842a]">
                Summary / <span className="text-[#4a4338]">{summary.status}</span>
                {summary.engine && (
                  <span
                    className={`ml-2 rounded-full px-2 py-0.5 text-[10px] font-semibold ${
                      summary.aiUsed ? "bg-[#1f6b45]/10 text-[#1f6b45]" : "bg-[#f6f0e4] text-[#8a5a18]"
                    }`}
                  >
                    {summary.aiUsed ? `AI / ${summary.engine}` : "Template fallback"}
                  </span>
                )}
                <span className="ml-2 text-[10px] text-[#4a4338]">DPDP 2023 Compliant • Secure</span>
              </p>
              <div className="flex flex-wrap gap-2">
                <button
                  type="button"
                  onClick={() => setShowBilingual(!showBilingual)}
                  className="rounded-full bg-[#e8d5a3] px-3 py-1.5 text-xs font-medium text-[#08363a]"
                >
                  {showBilingual ? "English" : "हिंदी / Bilingual"}
                </button>
                <button
                  type="button"
                  onClick={viewFhirBundle}
                  className="rounded-full bg-[#08363a] px-3 py-1.5 text-xs font-medium text-white"
                >
                  View FHIR Bundle (ABDM)
                </button>
                <button
                  type="button"
                  disabled={genBusy}
                  onClick={() => void generateSummary()}
                  className="inline-flex items-center gap-2 rounded-full bg-[#f6f0e4] px-4 py-2 text-xs font-medium text-[#08363a] transition hover:bg-[#efe4cf] disabled:opacity-50"
                >
                  {genBusy ? "Regenerating..." : "Regenerate summary"}
                </button>
              </div>
            </div>
            {showBilingual && summary && (
              <div className="rounded-2xl bg-[#f6f0e4] p-4 text-sm">
                <p className="text-xs uppercase text-[#c9842a]">Patient Audio Confirmation (Hindi) - Bilingual Output</p>
                <p className="mt-2">नमस्ते {patient.fullName}, आपकी मुख्य शिकायत {summary.chiefComplaint} है। डॉक्टर ने आपका विवरण देखा है। कृपया परामर्श कक्ष में प्रतीक्षा करें।</p>
                <p className="mt-1 text-xs text-[#4a4338]">English: Hello {patient.fullName}, your chief complaint is {summary.chiefComplaint}. Doctor has reviewed your history. Please wait in consultation room. (TTS via Bhashini future)</p>
              </div>
            )}

            {FIELDS.map((f) => (
              <label key={f.key} className="block">
                <span className="text-xs uppercase tracking-[0.16em] text-[#c9842a]">{f.label}</span>
                <textarea
                  value={fields[f.key] ?? ""}
                  onChange={(e) => setFields((curr) => ({ ...curr, [f.key]: e.target.value }))}
                  rows={f.key === "hpi" || f.key === "investigationsSummary" ? 5 : 2}
                  className="mt-1.5 w-full rounded-2xl border border-[#1b1712]/10 bg-[#fffdf7] px-4 py-3 text-[15px] leading-relaxed"
                />
              </label>
            ))}

            {ayush && (
              <section className="rounded-[28px] bg-[#08363a] p-6 text-[#f6f0e4]">
                <p className="text-xs uppercase tracking-[0.18em] text-[#e8d5a3]">Dashavidha Pariksha</p>
                <div className="mt-4 grid gap-3 md:grid-cols-2">
                  {Object.entries(ayush)
                    .filter(([, v]) => v)
                    .map(([k, v]) => (
                      <div key={k}>
                        <p className="text-[11px] uppercase tracking-wider text-[#e8d5a3]/80">{k}</p>
                        <p className="mt-0.5 text-sm">{v}</p>
                      </div>
                    ))}
                </div>
              </section>
            )}

            <label className="block">
              <span className="text-xs uppercase tracking-[0.16em] text-[#0f5c61]">Advice for patient (shown in their portal)</span>
              <textarea
                value={advice}
                onChange={(e) => setAdvice(e.target.value)}
                rows={3}
                className="mt-1.5 w-full rounded-2xl border border-[#0f5c61]/20 bg-[#f0f7f7] px-4 py-3"
                placeholder="e.g. Take medicines after food. Blood test before next visit. Come back in 1 week."
              />
            </label>

            <label className="block">
              <span className="text-xs uppercase tracking-[0.16em] text-[#c9842a]">Physician note (not shown to patient)</span>
              <textarea
                value={notes}
                onChange={(e) => setNotes(e.target.value)}
                rows={4}
                className="mt-1.5 w-full rounded-2xl border border-[#1b1712]/10 bg-[#fffdf7] px-4 py-3"
                placeholder="Plan, differentials, orders..."
              />
            </label>

            <div className="flex flex-wrap items-center gap-3">
              <input
                value={reviewedBy}
                onChange={(e) => setReviewedBy(e.target.value)}
                className="h-12 rounded-full border border-[#1b1712]/10 bg-white px-4"
                placeholder="Your name"
              />
              <button
                type="button"
                disabled={busy}
                onClick={() => void save(false)}
                className="h-12 rounded-full bg-[#f6f0e4] px-5 font-medium"
              >
                Save amendments
              </button>
              <button
                type="button"
                disabled={busy}
                onClick={() => void save(true)}
                className="h-12 rounded-full bg-[#0f5c61] px-6 font-semibold text-white"
              >
                Confirm to HIS / ABHA
              </button>
            </div>
            {message && <p className="text-sm text-[#1f6b45]">{message}</p>}
            {genStatus && <p className={`text-sm ${genStatus.kind === "error" ? "text-[#b42318]" : genStatus.kind === "ok" ? "text-[#1f6b45]" : "text-[#8a5a18]"}`}>{genStatus.message}</p>}
          </div>
        )}
      </div>

      <aside className="space-y-5">
        <section className="rounded-[28px] bg-[#fffdf7] p-5 ring-1 ring-[#1b1712]/8">
          <h2 className="text-xs uppercase tracking-[0.16em] text-[#c9842a]">Consent ledger</h2>
          <ul className="mt-3 space-y-2 text-sm">
            {consents.map((c) => (
              <li key={c.id} className="flex justify-between gap-2">
                <span className="capitalize">{c.consentType.replace(/_/g, " ")}</span>
                <span className={c.granted ? "text-[#1f6b45]" : "text-[#b42318]"}>{c.granted ? "granted" : "denied"}</span>
              </li>
            ))}
          </ul>
        </section>

        <section className="rounded-[28px] bg-[#fffdf7] p-5 ring-1 ring-[#1b1712]/8">
          <h2 className="text-xs uppercase tracking-[0.16em] text-[#c9842a]">Abnormal labs</h2>
          <ul className="mt-3 space-y-2 text-sm">
            {labs.filter((l) => l.abnormal).map((l) => (
              <li key={`${l.name}-${l.when}`} className="flex justify-between gap-2">
                <span>{l.name} <span className="text-[#b42318]">{l.value}{l.flag === "high" ? " up" : " down"}</span></span>
                <span className="text-xs text-[#4a4338]">{l.when}</span>
              </li>
            ))}
            {labs.filter((l) => l.abnormal).length === 0 && <li className="text-[#4a4338]">None flagged</li>}
          </ul>
        </section>

        <section className="rounded-[28px] bg-[#fffdf7] p-5 ring-1 ring-[#1b1712]/8">
          <h2 className="text-xs uppercase tracking-[0.16em] text-[#c9842a]">Document timeline</h2>
          <ol className="mt-3 space-y-3">
            {timeline.map((d) => (
              <li key={d.id} className="border-l-2 border-[#c9842a]/50 pl-3">
                <p className="text-xs text-[#4a4338]">{d.documentDate}</p>
                <p className="text-sm font-medium">{d.fileName}</p>
                <p className="text-xs text-[#4a4338]">{d.facilityName}</p>
                {d.extractedJson?.diagnoses?.length ? <p className="mt-1 text-xs">{d.extractedJson.diagnoses.join(" | ")}</p> : null}
              </li>
            ))}
            {timeline.length === 0 && <p className="text-sm text-[#4a4338]">No papers attached.</p>}
          </ol>
        </section>

        <section className="rounded-[28px] bg-[#08363a] p-5 text-[#f6f0e4]">
          <h2 className="text-xs uppercase tracking-[0.16em] text-[#e8d5a3]">HIS / FHIR events</h2>
          <ul className="mt-3 space-y-2 text-xs">
            {events.map((e) => (
              <li key={e.id}>
                <p className="font-medium">{e.eventType}</p>
                <p className="text-[#f6f0e4]/70">{new Date(e.createdAt).toLocaleString("en-IN")}</p>
              </li>
            ))}
            {events.length === 0 && <li>Nothing pushed yet - confirm to file.</li>}
          </ul>
        </section>
      </aside>

      {showFhir && fhirJson && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4">
          <div className="max-h-[85vh] w-full max-w-3xl overflow-auto rounded-3xl bg-white p-6 shadow-2xl">
            <div className="flex items-center justify-between border-b pb-3">
              <h3 className="font-bold text-[#08363a]">ABDM FHIR Bundle - DocumentBundle (NDHM)</h3>
              <button onClick={() => setShowFhir(false)} className="rounded-full bg-[#f6f0e4] px-3 py-1 text-xs">Close</button>
            </div>
            <p className="mt-3 text-xs text-[#4a4338]">This bundle is pushed to HIS + ABHA PHR via ABDM HIE. ResourceType: Bundle, Type: document, Profile: https://nrces.in/ndhm/fhir/r4/StructureDefinition/DocumentBundle</p>
            <pre className="mt-3 max-h-96 overflow-auto rounded-xl bg-[#f6f0e4] p-4 text-xs">{JSON.stringify(fhirJson, null, 2)}</pre>
            <div className="mt-4 flex gap-2">
              <button onClick={() => navigator.clipboard.writeText(JSON.stringify(fhirJson, null, 2))} className="rounded-full bg-[#0f5c61] px-4 py-2 text-xs text-white">Copy FHIR JSON</button>
              <a href={`data:application/json;charset=utf-8,${encodeURIComponent(JSON.stringify(fhirJson, null, 2))}`} download={`fhir-bundle-${patient.abhaId || patient.id}.json`} className="rounded-full bg-[#e8d5a3] px-4 py-2 text-xs text-[#08363a]">Download Bundle</a>
            </div>
            <p className="mt-3 text-[11px] text-[#4a4338]">ABDM Sandbox: POST https://dev.abdm.gov.in/api/hie/bundle with Bearer token. Currently mock, ready for production integration.</p>
          </div>
        </div>
      )}
    </main>
  );
}